const User = require('../models/userModel');
const catchAsync = require('../utils/catchAsync');

// exports.checkUser = (req, res, next) => {
//   const user = req.body;

//   if (!user.userName || !user.password) {
//     res.status(403).json({
//       status: 'error',
//       message: 'Invalid username or password',
//     });
//   }
//   next();
// };

exports.getAllUsers = catchAsync(async (req, res, next) => {
  const users = await User.find();

  res.status(200).json({
    status: 'success',
    results: users.length,
    data: {
      users,
    },
  });
});
exports.getUser = (req, res) => {
  res.status(500).json({
    status: 'error',
    message: 'This route is not yet defined!',
  });
};
exports.createUser = (req, res) => {
  res.status(500).json({
    status: 'error',
    message: 'This route is not yet defined!',
  });
};
exports.updateUser = (req, res) => {
  res.status(500).json({
    status: 'error',
    message: 'This route is not yet defined!',
  });
};
exports.deleteUser = (req, res) => {
  res.status(500).json({
    status: 'error',
    message: 'This route is not yet defined!',
  });
};
